---
abstract: 'Module designed to query the ADS'
author:
  - 'Alasdair Allan <aa@astro.ex.ac.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Astro-ADS
no_index:
  directory:
    - t
    - inc
requires:
  LWP: 5.53
  Net::Domain: 2.13
  Pod::Usage: 1.14
  Test::More: 0.65
version: 1.25
